import type { RecentLedgerEntry } from './recent-ledger-row';

export const RECENT_LEDGER_ENTRIES: RecentLedgerEntry[] = [
  {
    id: '1',
    merchant: 'Apple Store',
    amount: '-$1,299.00',
    meta: 'TECHNOLOGY • 2:45 PM',
    dateLabel: 'OCT 12',
    icon: 'laptop-mac',
    iconColor: '#00327D',
    amountTone: 'debit',
  },
  {
    id: '2',
    merchant: 'Dividend Payout',
    amount: '+$450.25',
    meta: 'INVESTMENT • 11:20 AM',
    dateLabel: 'OCT 11',
    icon: 'trending-up',
    iconColor: '#4EDEA3',
    amountTone: 'credit',
  },
  {
    id: '3',
    merchant: 'The Gilded Fork',
    amount: '-$240.50',
    meta: 'DINING • 8:15 PM',
    dateLabel: 'OCT 10',
    icon: 'restaurant',
    iconColor: '#00327D',
    amountTone: 'debit',
  },
  {
    id: '4',
    merchant: 'Spotify Premium',
    amount: '-$9.99',
    meta: 'SUBSCRIPTION • 9:00 AM',
    dateLabel: 'OCT 9',
    icon: 'music-note',
    iconColor: '#00327D',
    amountTone: 'debit',
  },
  {
    id: '5',
    merchant: 'Electricity Bill',
    amount: '-$75.80',
    meta: 'UTILITIES • 1:30 PM',
    dateLabel: 'OCT 8',
    icon: 'bolt',
    iconColor: '#00327D',
    amountTone: 'debit',
  },
  {
    id: '6',
    merchant: 'Amazon Purchase',
    amount: '-$59.99',
    meta: 'E-COMMERCE • 3:00 PM',
    dateLabel: 'OCT 7',
    icon: 'shopping-cart',
    iconColor: '#00327D',
    amountTone: 'debit',
  },
  {
    id: '7',
    merchant: 'Gym Membership',
    amount: '-$45.00',
    meta: 'HEALTH • 5:30 PM',
    dateLabel: 'OCT 6',
    icon: 'fitness-center',
    iconColor: '#00327D',
    amountTone: 'debit',
  },
  {
    id: '8',
    merchant: 'Book Sale',
    amount: '+$12.99',
    meta: 'ENTERTAINMENT • 12:15 PM',
    dateLabel: 'OCT 5',
    icon: 'menu-book',
    iconColor: '#4EDEA3',
    amountTone: 'credit',
  },
];
