import { StyleSheet } from 'react-native';

export const changePasswordStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F8F9FF' },
  container: { flex: 1 },
  content: { paddingHorizontal: 24, paddingTop: 24, paddingBottom: 44, gap: 24 },
  headerCard: { paddingHorizontal: 12, paddingTop: 20, paddingBottom: 12, alignItems: 'center', gap: 12 },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 9999,
    backgroundColor: '#DCE9FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  pageTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 38,
    lineHeight: 44,
    letterSpacing: -0.5,
    textAlign: 'center',
    color: '#002046',
  },
  pageSubtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
    color: '#44474E',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(196, 198, 207, 0.4)',
    padding: 16,
    gap: 18,
    shadowColor: '#1B365D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  formCardTopGradient: { height: 4, borderTopLeftRadius: 11, borderTopRightRadius: 11, marginHorizontal: -15, marginTop: -15, marginBottom: 10 },
  fieldBlock: { gap: 8 },
  fieldLabel: { fontFamily: 'Manrope-Medium', fontSize: 12, lineHeight: 16, color: '#0B1C30' },
  inputWrap: {
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#C4C6CF',
    backgroundColor: '#F8F9FF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 10,
  },
  inputWrapError: {
    borderColor: '#BA1A1A',
  },
  input: { flex: 1, fontFamily: 'Manrope-Regular', fontSize: 16, lineHeight: 20, color: '#0B1C30' },
  errorText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#BA1A1A',
  },
  separator: { height: 1, backgroundColor: 'rgba(196, 198, 207, 0.3)' },
  strengthWrap: { gap: 8, paddingTop: 4 },
  strengthBars: { flexDirection: 'row', gap: 4 },
  strengthBar: { flex: 1, height: 6, borderRadius: 9999, backgroundColor: '#D3E4FE' },
  strengthBarActive: { backgroundColor: '#0051D5' },
  strengthText: { fontFamily: 'Manrope-Medium', fontSize: 12, lineHeight: 16, color: '#44474E' },
  strengthStrong: { color: '#0051D5', fontFamily: 'Manrope-Bold' },
  requirementsCard: {
    backgroundColor: '#EFF4FF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(196, 198, 207, 0.3)',
    padding: 16,
    gap: 10,
  },
  requirementsTitle: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#0B1C30',
  },
  requirementRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  requirementText: { flex: 1, fontFamily: 'Manrope-Regular', fontSize: 14, lineHeight: 20, color: '#44474E' },
  actionWrap: { paddingTop: 16, gap: 12 },
  primaryBtn: {
    height: 48,
    borderRadius: 16,
    backgroundColor: '#0051D5',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  primaryBtnDisabled: {
    backgroundColor: '#9EB9E8',
  },
  primaryBtnText: { fontFamily: 'Manrope-SemiBold', fontSize: 14, lineHeight: 18, letterSpacing: 0.4, color: '#FFFFFF' },
  secondaryBtn: {
    height: 48,
    borderRadius: 16,
    backgroundColor: '#EFF4FF',
    borderWidth: 1,
    borderColor: '#EFF4FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtnText: { fontFamily: 'Manrope-SemiBold', fontSize: 14, lineHeight: 18, letterSpacing: 0.4, color: '#0051D5' },
  footer: { paddingTop: 10, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6 },
  footerText: { fontFamily: 'Manrope-Regular', fontSize: 14, lineHeight: 20, color: '#44474E' },
});
