import { StyleSheet } from 'react-native';

export const settingsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F8FC',
  },
  container: {
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
    gap: 16,
  },
  profileCard: {
    minHeight: 112,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 2,
  },
  profileLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flexShrink: 1,
  },
  avatarWrap: {
    width: 64,
    height: 64,
    position: 'relative',
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 9999,
    backgroundColor: '#1E293B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontFamily: 'Inter-Bold',
    fontSize: 20,
    lineHeight: 24,
    color: '#FFFFFF',
  },
  avatarBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    width: 24,
    height: 24,
    borderRadius: 9999,
    backgroundColor: '#4EDEA3',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  profileMeta: {
    gap: 4,
    flexShrink: 1,
  },
  profileName: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 22,
    color: '#191C1E',
  },
  memberPill: {
    alignSelf: 'flex-start',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: 'rgba(0, 50, 125, 0.05)',
  },
  memberPillText: {
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: '#00327D',
  },
  ledgerBentoRow: {
    height: 124,
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 16,
  },
  ledgerBentoCard: {
    flex: 1,
    borderRadius: 12,
    padding: 12,
    gap: 12,
  },
  ledgerBentoCardLight: {
    backgroundColor: '#F2F4F6',
  },
  ledgerBentoCardDark: {
    backgroundColor: '#00327D',
  },
  ledgerBentoIconWrap: {
    height: 46,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  ledgerBentoTextWrap: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  ledgerBentoLabelLight: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: '#434653',
  },
  ledgerBentoValueLight: {
    fontFamily: 'Inter-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#191C1E',
  },
  ledgerBentoLabelDark: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: '#FFFFFF',
  },
  ledgerBentoValueDark: {
    fontFamily: 'Inter-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  settingsGroupsRoot: {
    width: '100%',
    gap: 32,
  },
  settingsGroupBlock: {
    gap: 16,
  },
  settingsGroupHeading: {
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: 'rgba(67, 70, 83, 0.5)',
  },
  settingsGroupList: {
    gap: 8,
  },
  settingsOptionRow: {
    minHeight: 72,
    backgroundColor: '#F2F4F6',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flexShrink: 1,
  },
  settingsOptionIconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  settingsOptionMeta: {
    flexShrink: 1,
    gap: 0,
  },
  settingsOptionTitle: {
    fontFamily: 'Inter-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#191C1E',
  },
  settingsOptionSubtitle: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#434653',
  },
  settingsToggleTrack: {
    width: 40,
    height: 20,
    borderRadius: 9999,
    backgroundColor: '#C3C6D5',
    padding: 4,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  settingsToggleOnTrack: {
    backgroundColor: '#4EDEA3',
    alignItems: 'flex-end',
  },
  settingsToggleThumb: {
    width: 12,
    height: 12,
    borderRadius: 9999,
    backgroundColor: '#FFFFFF',
  },
  signOutButton: {
    height: 56,
    borderRadius: 12,
    backgroundColor: '#FFDAD6',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  signOutText: {
    fontFamily: 'Inter-Bold',
    fontSize: 16,
    lineHeight: 24,
    color: '#93000A',
    textAlign: 'center',
  },
  settingsVersionWrap: {
    alignItems: 'center',
    paddingBottom: 48,
  },
  settingsVersionText: {
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: '#737784',
    textAlign: 'center',
  },
});
