import { StyleSheet } from 'react-native';

export const newPasswordStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f5f8ff',
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 14,
  },
  heroCard: {
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dbe6fb',
    padding: 18,
    gap: 8,
  },
  eyebrow: {
    alignSelf: 'flex-start',
    borderRadius: 9999,
    backgroundColor: '#e7efff',
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: '#18407e',
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1,
  },
  title: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 30,
    lineHeight: 36,
    color: '#091a35',
    letterSpacing: -0.4,
  },
  subtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#5e6f87',
    lineHeight: 22,
  },
  formWrap: {
    borderRadius: 22,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dbe6fb',
    padding: 18,
    gap: 10,
    marginTop: 4,
  },
  label: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#24364f',
    marginBottom: 6,
  },
  input: {
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#cbdaf7',
    borderRadius: 14,
    color: '#0f1f39',
    backgroundColor: '#f8fbff',
    marginBottom: 8,
  },
  hintTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#415f90',
  },
  hint: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: '#6f83a1',
    marginBottom: 4,
  },
  ruleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  rulePill: {
    borderRadius: 9999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#e7efff',
  },
  rulePillText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 11,
    color: '#315180',
  },
});
