import { StyleSheet } from 'react-native';

export const overviewStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  overviewInner: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 32,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingTop: 8,
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginRight: 12,
  },
  headerAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#e2e8f0',
  },
  headerAvatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#0d9488',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAvatarInitials: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 15,
    color: '#fff',
  },
  headerTitle: {
    flex: 1,
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#0f172a',
    letterSpacing: -0.2,
  },
  headerBellHit: {
    padding: 8,
    marginRight: -4,
  },
  heading: {
    fontFamily: 'Manrope-Bold',
    fontSize: 24,
    color: '#0f172a',
    marginBottom: 8,
  },
  subheading: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    color: '#64748b',
  },
  summaryCard: {
    marginTop: 20,
    borderRadius: 24,
    padding: 24,
    gap: 16,
    overflow: 'hidden',
    alignSelf: 'stretch',
    width: '100%',
    minHeight: 218,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 6,
  },
  summaryGlow: {
    position: 'absolute',
    width: 192,
    height: 192,
    borderRadius: 96,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    right: -48,
    top: -48,
    zIndex: 0,
  },
  summaryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    zIndex: 1,
  },
  summaryPortfolioLabel: {
    flex: 1,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  summaryChangePill: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 9999,
    backgroundColor: 'rgba(78, 222, 163, 0.2)',
  },
  summaryChangeText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: '#4EDEA3',
  },
  summaryAmountBlock: {
    gap: 4,
    zIndex: 1,
  },
  summaryBalance: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -0.75,
    color: '#FFFFFF',
  },
  summaryValuationCaption: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'italic',
    color: 'rgba(255, 255, 255, 0.6)',
    opacity: 0.8,
  },
  summaryActions: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 16,
    paddingTop: 8,
    zIndex: 2,
  },
  summaryActionButton: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
  },
  summaryActionButtonPressed: {
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  summaryActionLabel: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 22,
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
  allocationsSection: {
    marginTop: 24,
    gap: 24,
    alignSelf: 'stretch',
    width: '100%',
  },
  allocationsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 28,
  },
  allocationsTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    lineHeight: 28,
    letterSpacing: -0.5,
    color: '#191C1E',
  },
  allocationsViewAll: {
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#00327D',
  },
  allocationsScrollContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingRight: 4,
  },
  allocationCard: {
    width: 163,
    minHeight: 169,
    backgroundColor: '#F2F4F6',
    borderRadius: 20,
    padding: 16,
  },
  allocationCardSpacing: {
    marginRight: 8,
  },
  allocationIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 9999,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  allocationCategoryName: {
    marginTop: 8,
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#191C1E',
  },
  allocationSpent: {
    marginTop: 4,
    marginBottom: 8,
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    color: '#00327D',
  },
  allocationProgressTrack: {
    height: 6,
    borderRadius: 9999,
    backgroundColor: '#E0E3E5',
    overflow: 'hidden',
  },
  allocationProgressFill: {
    height: '100%',
    borderRadius: 9999,
  },
  allocationRemaining: {
    marginTop: 4,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  spendingTrendCard: {
    marginTop: 24,
    alignSelf: 'stretch',
    width: '100%',
    minHeight: 283,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 4,
  },
  spendingTrendHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 28,
  },
  spendingTrendTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.45,
    color: '#191C1E',
  },
  spendingTrendDots: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
  },
  spendingTrendDot: {
    width: 8,
    height: 8,
    borderRadius: 9999,
    backgroundColor: '#E0E3E5',
  },
  spendingTrendDotActive: {
    backgroundColor: '#0047AB',
  },
  spendingTrendSubtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#94A3B8',
  },
  spendingTrendChartWrap: {
    width: '100%',
    minHeight: 128,
    paddingTop: 16,
  },
  spendingTrendAxis: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingTop: 8,
    width: '100%',
  },
  spendingTrendAxisLabel: {
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#94A3B8',
  },
  recentLedgerSection: {
    marginTop: 24,
    gap: 24,
    alignSelf: 'stretch',
    width: '100%',
  },
  recentLedgerHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 40,
  },
  recentLedgerTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.45,
    color: '#191C1E',
  },
  recentLedgerViewAllHit: {
    padding: 12,
    marginVertical: -12,
    marginRight: -12,
  },
  recentLedgerViewAll: {
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#00327D',
  },
  recentLedgerSeparator: {
    height: 16,
  },
  recentLedgerRow: {
    minHeight: 80,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#F2F4F6',
    borderRadius: 16,
    gap: 16,
  },
  recentLedgerRowMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    minWidth: 0,
  },
  recentLedgerIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 2,
  },
  recentLedgerTextBlock: {
    flex: 1,
    justifyContent: 'space-between',
    gap: 2,
    minHeight: 48,
    minWidth: 0,
  },
  recentLedgerMerchant: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    lineHeight: 24,
    color: '#191C1E',
  },
  recentLedgerMeta: {
    fontFamily: 'Manrope-Regular',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#64748B',
  },
  recentLedgerRight: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 2,
    minHeight: 48,
    marginLeft: 8,
  },
  recentLedgerAmount: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'right',
  },
  recentLedgerAmountDebit: {
    color: '#BA1A1A',
  },
  recentLedgerAmountCredit: {
    color: '#00593C',
  },
  recentLedgerDate: {
    fontFamily: 'Manrope-Regular',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    textAlign: 'right',
    color: '#94A3B8',
  },
  quickFabRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    elevation: 20,
  },
  quickFabBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
    zIndex: 2,
  },
  quickFabCluster: {
    position: 'absolute',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    zIndex: 3,
  },
  quickFabMainOuter: {
    zIndex: 4,
  },
  quickFabMain: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: '#0047AB',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  quickFabSatWrap: {
    zIndex: 3,
  },
  quickFabSatellite: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  card: {
    marginTop: 24,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  cardTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 16,
    color: '#0f172a',
  },
  cardBody: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#64748b',
    marginTop: 8,
    lineHeight: 20,
  },
});
