import { StyleSheet } from 'react-native';

export const addAllocationStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F9FB',
  },
  container: {
    flex: 1,
  },
  main: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 140,
    gap: 24,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    gap: 12,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 2,
  },
  label: {
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#737784',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  amountSymbol: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 36,
    lineHeight: 40,
    color: '#C3C6D5',
    marginRight: 8,
  },
  amountInput: {
    flex: 1,
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 56,
    lineHeight: 64,
    color: '#00327D',
  },
  amountTag: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#00327D',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  amountTagText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: '#FFFFFF',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  continueButton: {
    height: 68,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D5E0F8',
  },
  continueText: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 18,
    lineHeight: 28,
    color: '#0145A5',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  categoryButton: {
    width: '30.8%',
    minHeight: 80,
    borderRadius: 16,
    backgroundColor: '#F2F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  categoryButtonActive: {
    backgroundColor: '#D5E0F8',
  },
  categoryText: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    lineHeight: 16,
    color: '#434653',
  },
  categoryTextActive: {
    color: '#00327D',
    fontFamily: 'Manrope-Bold',
  },
  sectionTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    color: '#00327D',
  },
  segmented: {
    backgroundColor: '#F2F4F6',
    borderRadius: 12,
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  segmentedBtn: {
    flex: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
  },
  segmentedBtnActive: {
    backgroundColor: '#D5E0F8',
  },
  segmentedText: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    color: '#191C1E',
  },
  segmentedTextActive: {
    fontFamily: 'Manrope-Bold',
    color: '#00327D',
  },
  inputRow: {
    marginTop: 8,
    backgroundColor: '#F2F4F6',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 52,
    justifyContent: 'center',
  },
  textInput: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#191C1E',
  },
  toggleRow: {
    marginTop: 8,
    backgroundColor: '#F2F4F6',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toggleLabel: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#191C1E',
  },
  thresholdBox: {
    marginTop: 8,
    backgroundColor: '#F2F4F6',
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  thresholdTitle: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#00327D',
  },
  thresholdMeta: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 10,
    lineHeight: 15,
    textTransform: 'uppercase',
    color: '#586377',
    marginTop: 2,
  },
  notesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  notesInput: {
    minHeight: 72,
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#6B7280',
  },
  actionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.85)',
  },
  primaryButton: {
    height: 62,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00327D',
  },
  primaryButtonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#FFFFFF',
  },
});
