import { StyleSheet } from 'react-native';

export const allocationStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F9FB',
  },
  container: {
    flex: 1,
  },
  main: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
    gap: 16,
  },
  filtersContainer: {
    maxHeight: 44,
  },
  filtersContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 4,
    gap: 4,
    alignItems: 'center',
    position: 'relative',
  },
  filterButton: {
    minWidth: 42,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#FBFBFB',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  filterButtonActive: {
    backgroundColor: '#EEF3FF',
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 1,
  },
  filterText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#586377',
  },
  filterTextActive: {
    color: '#00327D',
  },
  moreFade: {
    width: 25,
    height: 36,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(195, 198, 213, 0.1)',
    padding: 24,
    gap: 4,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.02,
    shadowRadius: 40,
    elevation: 2,
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  iconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pill: {
    borderRadius: 9999,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  pillText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cardTitle: {
    paddingTop: 20,
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    lineHeight: 28,
    color: '#191C1E',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  amountMain: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 24,
    lineHeight: 32,
    color: '#191C1E',
  },
  amountBudget: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#434653',
  },
  progressTopRow: {
    paddingTop: 20,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  progressMeta: {
    fontFamily: 'Manrope-Bold',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: -0.55,
    textTransform: 'uppercase',
    color: '#434653',
  },
  progressMetaPositive: {
    color: '#586377',
  },
  progressMetaDanger: {
    color: '#BA1A1A',
  },
  progressTrack: {
    height: 12,
    borderRadius: 9999,
    backgroundColor: '#E0E3E5',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 9999,
  },
  newCard: {
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(195, 198, 213, 0.15)',
    padding: 32,
    alignItems: 'center',
    gap: 16,
  },
  newCardIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D5E0F8',
  },
  newCardBody: {
    alignItems: 'center',
    gap: 2,
  },
  newCardTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    color: '#191C1E',
  },
  newCardSubtitle: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#586377',
  },
  quickAddButton: {
    width: '100%',
    height: 54,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00327D',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 2,
  },
  quickAddText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 22,
    color: '#FFFFFF',
  },
});
