import { StyleSheet } from 'react-native';

export const fabsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F9FB',
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    height: 64,
    backgroundColor: '#F3F5F7',
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F2F4F6',
  },
  backButton: {
    width: 38,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  title: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 20,
    color: '#00327D',
  },
  modeToggle: {
    marginTop: 16,
    marginHorizontal: 24,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 4,
    gap: 4,
    position: 'relative',
    overflow: 'hidden',
  },
  modeIndicator: {
    position: 'absolute',
    left: 4,
    top: 4,
    bottom: 4,
    borderRadius: 8,
    backgroundColor: '#EEF3FF',
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 2,
  },
  modeButton: {
    flex: 1,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FBFBFB',
  },
  modeButtonActive: {
    backgroundColor: '#EEF3FF',
  },
  modeText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    color: '#586377',
  },
  modeTextActive: {
    color: '#00327D',
  },
  main: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 140,
    gap: 24,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    gap: 16,
  },
  label: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#737784',
  },
  input: {
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F2F4F6',
    paddingHorizontal: 12,
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    color: '#1F2937',
  },
  amountCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    gap: 12,
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  amountCurrency: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 28,
    color: '#C3C6D5',
    marginRight: 8,
  },
  amountValue: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 56,
    lineHeight: 66,
    color: '#00327D',
  },
  amountTag: {
    marginLeft: 'auto',
    backgroundColor: '#00327D',
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  amountTagText: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    color: '#FFFFFF',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  keypad: {
    gap: 10,
  },
  keypadRow: {
    flexDirection: 'row',
    gap: 10,
  },
  key: {
    flex: 1,
    height: 58,
    borderRadius: 12,
    backgroundColor: '#F2F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 24,
    color: '#191C1E',
  },
  notesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  notesInput: {
    minHeight: 80,
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    color: '#6B7280',
  },
  captureCard: {
    height: 530,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(0, 71, 171, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    gap: 16,
  },
  captureTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    textAlign: 'center',
    color: '#191C1E',
  },
  fabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  primaryAction: {
    height: 62,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00327D',
  },
  primaryActionText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#FFFFFF',
  },
  allocationList: {
    alignSelf: 'stretch',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    zIndex: 10,
  },
  allocationItem: {
    height: 43,
    borderRadius: 12,
    backgroundColor: '#F2F4F6',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  allocationItemText: {
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    color: '#74777F',
  },
});
