import { StyleSheet } from 'react-native';

export const budgetStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F8FC',
  },
  container: {
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
    gap: 16,
  },
  monthlyBurnCard: {
    backgroundColor: '#0C48A2',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 2,
    gap: 32,
  },
  monthlyBurnTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  monthlyBurnTitleBlock: {
    gap: 2,
  },
  monthlyBurnLabel: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#E0E3E5',
  },
  monthlyBurnAmount: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: -0.5,
    color: '#E0E3E5',
  },
  monthlyBurnStatusPill: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 9999,
    backgroundColor: '#00593C',
    borderWidth: 1,
    borderColor: 'rgba(78, 222, 163, 0.3)',
  },
  monthlyBurnStatusText: {
    fontFamily: 'Inter-Bold',
    fontSize: 9,
    lineHeight: 13,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: '#FFFFFF',
  },
  monthlyBurnProgressTrack: {
    height: 16,
    borderRadius: 9999,
    backgroundColor: '#E0E3E5',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
  },
  monthlyBurnProgressFill: {
    width: '62%',
    height: '100%',
    borderRadius: 9999,
  },
  monthlyBurnBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  monthlyBurnMeta: {
    fontFamily: 'Inter-Medium',
    fontSize: 11,
    lineHeight: 15,
    color: '#E0E3E5',
  },
  velocityCard: {
    borderRadius: 24,
    backgroundColor: '#E5E7EB',
    padding: 16,
    gap: 14,
  },
  velocityHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  velocityHeadingWrap: {
    flex: 1,
    marginRight: 12,
    gap: 4,
  },
  velocityTitle: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 24,
    lineHeight: 30,
    letterSpacing: -0.4,
    color: '#191C1E',
  },
  velocitySubtitle: {
    fontFamily: 'Inter-Medium',
    fontSize: 14,
    lineHeight: 20,
    color: '#4A4E5C',
  },
  velocityPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#CBD5E1',
    borderRadius: 9999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 6,
  },
  velocityPillValue: {
    fontFamily: 'Inter-Bold',
    fontSize: 16,
    lineHeight: 22,
    color: '#06563A',
  },
  velocityChartWrap: {
    borderRadius: 20,
    backgroundColor: '#E5E7EB',
    overflow: 'hidden',
    paddingBottom: 4,
  },
  velocityAxisRow: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  velocityBarLabel: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.8,
    color: '#6D7280',
  },
  velocityRemainingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  velocityRemainingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 1,
  },
  velocityRemainingLabel: {
    fontFamily: 'Inter-Medium',
    fontSize: 16,
    lineHeight: 22,
    color: '#191C1E',
  },
  velocityRemainingValue: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 16,
    lineHeight: 30,
    color: '#06563A',
  },
  categorySection: {
    paddingVertical: 8,
    gap: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(195, 198, 213, 0.15)',
  },
  categoryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 2,
    gap: 24,
  },
  categoryLabel: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#737784',
  },
  categoryScroller: {
    marginHorizontal: -2,
  },
  categoryScrollerContent: {
    paddingHorizontal: 2,
    gap: 12,
  },
  categoryTile: {
    width: 90,
    height: 90,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  categoryTileActive: {
    backgroundColor: '#F2F4F6',
  },
  categoryTileInactive: {
    backgroundColor: '#F2F4F6',
  },
  categoryTileIcon: {
    marginBottom: 8,
  },
  categoryTileText: {
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
  },
  categoryTileTextActive: {
    fontFamily: 'Inter-Bold',
    color: '#00327D',
  },
  categoryTileTextInactive: {
    fontFamily: 'Inter-Medium',
    color: '#434653',
  },
  addCategoryButtonOuter: {
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 2,
  },
  addCategoryButton: {
    height: 62,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  addCategoryText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 22,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  categorySummarySection: {
    gap: 24,
    paddingBottom: 12,
  },
  categorySummaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categorySummaryTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.45,
    color: '#191C1E',
  },
  categorySummaryViewAllButton: {
    minHeight: 40,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categorySummaryViewAllText: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#00327D',
  },
  categorySummaryList: {
    gap: 16,
  },
  categorySummaryCard: {
    backgroundColor: '#F2F4F6',
    borderRadius: 20,
    padding: 16,
    gap: 8,
  },
  categorySummaryIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 9999,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categorySummaryBody: {
    gap: 8,
  },
  categorySummaryName: {
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#191C1E',
  },
  categorySummaryTrack: {
    height: 6,
    borderRadius: 9999,
    backgroundColor: '#E0E3E5',
    overflow: 'hidden',
  },
  categorySummaryFill: {
    height: '100%',
    borderRadius: 9999,
  },
  categorySummaryFillPrimary: {
    backgroundColor: '#00327D',
  },
  categorySummaryFillDanger: {
    backgroundColor: '#BA1A1A',
  },
  categorySummaryBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categorySummaryBudget: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 28,
    color: '#00327D',
  },
  categorySummaryLeft: {
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  categorySummaryLeftNeutral: {
    color: '#434653',
  },
  categorySummaryLeftDanger: {
    color: '#BA1A1A',
  },
});
