import { StyleSheet } from 'react-native';

export const identityVerificationStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FF',
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  bgBlobTop: {
    position: 'absolute',
    width: 195,
    height: 442,
    left: -39,
    top: -88,
    backgroundColor: '#AEC7F7',
    opacity: 0.2,
    borderRadius: 9999,
  },
  bgBlobBottom: {
    position: 'absolute',
    width: 156,
    height: 354,
    right: -39,
    bottom: -88,
    backgroundColor: '#DBE1FF',
    opacity: 0.3,
    borderRadius: 9999,
  },
  main: {
    width: '100%',
    maxWidth: 400,
    minHeight: 660,
    zIndex: 2,
    justifyContent: 'space-between',
  },
  headerSection: {
    alignItems: 'center',
    gap: 8,
  },
  headerIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 9999,
    backgroundColor: '#D6E3FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontFamily: 'Manrope-Bold',
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: -0.64,
    color: '#002046',
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    lineHeight: 24,
    color: '#44474E',
    textAlign: 'center',
  },
  cameraArea: {
    alignItems: 'center',
    gap: 24,
  },
  instructionToast: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#DCE9FF',
    borderWidth: 1,
    borderColor: '#C4C6CF',
    borderRadius: 9999,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  instructionText: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.7,
    color: '#0B1C30',
  },
  viewportOuter: {
    width: 280,
    height: 280,
    borderRadius: 9999,
    borderWidth: 4,
    borderColor: '#0051D5',
    padding: 4,
    backgroundColor: '#FFFFFF',
    shadowColor: '#1B365D',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 32,
    elevation: 3,
  },
  viewportInner: {
    flex: 1,
    borderRadius: 9999,
    overflow: 'hidden',
    backgroundColor: '#D3E4FE',
  },
  cameraView: {
    flex: 1,
  },
  cameraPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D3E4FE',
  },
  cameraPlaceholderIcon: {
    opacity: 0.2,
  },
  securityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#E5EEFF',
    backgroundColor: '#FFFFFF',
    borderRadius: 9999,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  securityBadgeText: {
    fontFamily: 'Inter-Medium',
    fontSize: 12,
    lineHeight: 16,
    color: '#74777F',
  },
  actionSection: {
    gap: 16,
  },
  primaryButton: {
    height: 48,
    borderRadius: 8,
    backgroundColor: '#9FA8B7',
    opacity: 0.3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonReady: {
    opacity: 1,
    backgroundColor: '#0051D5',
  },
  primaryButtonText: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.7,
    color: '#FFFFFF',
  },
  cancelButton: {
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.7,
    color: '#0051D5',
  },
});
