import { StyleSheet } from 'react-native';

export const identityVerificationStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f5f8ff',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  bgBlobTop: {
    position: 'absolute',
    width: 195,
    height: 442,
    left: -39,
    top: -88,
    backgroundColor: '#aec7f7',
    opacity: 0.25,
    borderRadius: 9999,
  },
  bgBlobBottom: {
    position: 'absolute',
    width: 156,
    height: 354,
    right: -39,
    bottom: -88,
    backgroundColor: '#dbe1ff',
    opacity: 0.3,
    borderRadius: 9999,
  },
  main: {
    width: '100%',
    maxWidth: 400,
    minHeight: 640,
    zIndex: 2,
    justifyContent: 'space-between',
  },
  headerSection: {
    alignItems: 'center',
    gap: 9,
  },
  headerIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 9999,
    backgroundColor: '#dce8ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 34,
    lineHeight: 40,
    letterSpacing: -0.7,
    color: '#092044',
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    lineHeight: 23,
    color: '#4e607a',
    textAlign: 'center',
  },
  cameraArea: {
    alignItems: 'center',
    gap: 20,
  },
  instructionToast: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#dce9ff',
    borderWidth: 1,
    borderColor: '#bccde8',
    borderRadius: 9999,
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  instructionText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
    color: '#1a3a66',
  },
  viewportOuter: {
    width: 280,
    height: 280,
    borderRadius: 9999,
    borderWidth: 4,
    borderColor: '#0051d5',
    padding: 4,
    backgroundColor: '#ffffff',
    shadowColor: '#0e2b54',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 32,
    elevation: 3,
  },
  viewportInner: {
    flex: 1,
    borderRadius: 9999,
    overflow: 'hidden',
    backgroundColor: '#d3e4fe',
  },
  cameraView: {
    flex: 1,
  },
  cameraPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#d3e4fe',
  },
  cameraPlaceholderIcon: {
    opacity: 0.2,
  },
  securityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#d8e5fb',
    backgroundColor: '#ffffff',
    borderRadius: 9999,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  securityBadgeText: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    lineHeight: 18,
    color: '#5e6f88',
  },
  actionSection: {
    gap: 12,
  },
  primaryButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: '#97a7bf',
    opacity: 0.3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonReady: {
    opacity: 1,
    backgroundColor: '#0051d5',
  },
  primaryButtonText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#ffffff',
  },
  cancelButton: {
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eaf2ff',
  },
  cancelButtonText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#2f4e7b',
  },
});
