import { StyleSheet } from 'react-native';

export const insightsStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F8FC',
  },
  container: {
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
    gap: 16,
  },
  financialInsightsSection: {
    gap: 24,
  },
  financialInsightsHeader: {
    gap: 4,
  },
  financialInsightsEyebrow: {
    fontFamily: 'Inter-Bold',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.55,
    textTransform: 'uppercase',
    color: '#545F73',
  },
  financialInsightsTitle: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -0.75,
    color: '#00327D',
  },
  financialInsightsTabs: {
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F2F4F6',
    padding: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  financialInsightsTab: {
    flex: 1,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  financialInsightsTabActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 1,
  },
  financialInsightsTabText: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 14,
    lineHeight: 20,
    color: '#545F73',
    textAlign: 'center',
  },
  financialInsightsTabTextActive: {
    color: '#00327D',
  },
  monthlyOverviewSection: {
    gap: 20,
  },
  monthlyOverviewContent: {
    gap: 16,
  },
  monthlyOverviewEyebrow: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#545F73',
  },
  monthlyOverviewTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -0.9,
    color: '#191C1E',
  },
  monthlyOverviewBody: {
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    lineHeight: 26,
    color: '#434653',
  },
  monthlyOverviewSpentCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(195, 198, 213, 0.1)',
    borderRadius: 32,
    borderBottomLeftRadius: 0,
    padding: 24,
    gap: 8,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.02,
    shadowRadius: 20,
    elevation: 1,
  },
  monthlyOverviewSpentHeader: {
    gap: 0,
  },
  monthlyOverviewSpentLabel: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#545F73',
  },
  monthlyOverviewSpentAmount: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 30,
    lineHeight: 36,
    color: '#00327D',
  },
  monthlyOverviewTrack: {
    height: 6,
    borderRadius: 9999,
    backgroundColor: '#E0E3E5',
    overflow: 'hidden',
  },
  monthlyOverviewFill: {
    width: '64%',
    height: '100%',
  },
  monthlyOverviewMeta: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    lineHeight: 16,
    color: '#434653',
  },
  allocationCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(195, 198, 213, 0.15)',
    borderRadius: 24,
    padding: 20,
    gap: 20,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 1,
  },
  allocationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  allocationTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    lineHeight: 28,
    color: '#191C1E',
  },
  allocationViewAll: {
    fontFamily: 'Inter-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#00327D',
  },
  allocationContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  allocationDonutWrap: {
    width: 128,
    height: 128,
    alignItems: 'center',
    justifyContent: 'center',
  },
  allocationDonutCenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  allocationTotalLabel: {
    fontFamily: 'Inter-Bold',
    fontSize: 8,
    lineHeight: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#737784',
  },
  allocationTotalValue: {
    fontFamily: 'Inter-Bold',
    fontSize: 16,
    lineHeight: 21,
    color: '#00327D',
  },
  allocationLegend: {
    flex: 1,
    gap: 4,
  },
  allocationLegendRow: {
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  allocationLegendLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  allocationLegendDot: {
    width: 12,
    height: 12,
    borderRadius: 9999,
  },
  allocationLegendLabel: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 10,
    lineHeight: 20,
    color: '#191C1E',
    minWidth: 90,
  },
  allocationLegendValue: {
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    lineHeight: 20,
    color: '#191C1E',
  },
  smartSuggestionsOuter: {
    paddingTop: 16,
  },
  smartSuggestionsSection: {
    gap: 12,
  },
  smartSuggestionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smartSuggestionsTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
    lineHeight: 28,
    color: '#191C1E',
  },
  smartSuggestionsViewAll: {
    fontFamily: 'Inter-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#00327D',
  },
  smartSuggestionsList: {
    gap: 16,
  },
  smartSuggestionCard: {
    backgroundColor: '#F2F4F6',
    borderRadius: 20,
    padding: 16,
    gap: 16,
  },
  smartSuggestionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smartSuggestionIconWrapHigh: {
    backgroundColor: 'rgba(0, 63, 41, 0.1)',
  },
  smartSuggestionIconWrapStrategy: {
    backgroundColor: 'rgba(0, 50, 125, 0.1)',
  },
  smartSuggestionContent: {
    gap: 8,
  },
  smartSuggestionTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  smartSuggestionHeading: {
    flex: 1,
    fontFamily: 'Inter-Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#191C1E',
  },
  smartSuggestionTag: {
    borderRadius: 9999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  smartSuggestionTagHigh: {
    backgroundColor: 'rgba(0, 89, 60, 0.2)',
  },
  smartSuggestionTagStrategy: {
    backgroundColor: 'rgba(0, 71, 171, 0.1)',
  },
  smartSuggestionTagText: {
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  smartSuggestionTagTextHigh: {
    color: '#003F29',
  },
  smartSuggestionTagTextStrategy: {
    color: '#00327D',
  },
  smartSuggestionBody: {
    fontFamily: 'Inter-Medium',
    fontSize: 12,
    lineHeight: 20,
    color: '#434653',
  },
  smartSuggestionActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingTop: 8,
    alignSelf: 'flex-start',
  },
  smartSuggestionActionText: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: '#00327D',
  },
  smartGoalCard: {
    borderRadius: 32,
    padding: 32,
    gap: 24,
  },
  smartGoalRingWrap: {
    width: 160,
    height: 160,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smartGoalRingCenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smartGoalPercent: {
    fontFamily: 'Inter-Bold',
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
  },
  smartGoalLabel: {
    fontFamily: 'Inter-Bold',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: 'rgba(255, 255, 255, 0.6)',
  },
  smartGoalContent: {
    gap: 15,
    width: '100%',
  },
  smartGoalTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
  },
  smartGoalBody: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    lineHeight: 23,
    color: '#A5BDFF',
    maxWidth: 256,
  },
  smartGoalActionButton: {
    height: 43,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  smartGoalActionText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    lineHeight: 22,
    color: '#00327D',
    textAlign: 'center',
  },
});
