import { StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f4f8ff',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 24,
    justifyContent: 'space-between',
  },
  hero: {
    borderRadius: 28,
    paddingHorizontal: 22,
    paddingVertical: 26,
    backgroundColor: '#003e96',
    overflow: 'hidden',
    gap: 18,
    marginTop: 8,
  },
  glowTop: {
    position: 'absolute',
    top: -80,
    right: -50,
    width: 180,
    height: 180,
    borderRadius: 9999,
    backgroundColor: 'rgba(78,222,163,0.35)',
  },
  glowBottom: {
    position: 'absolute',
    bottom: -50,
    left: -30,
    width: 140,
    height: 140,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  badge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  badgeText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 11,
    color: '#d8e7ff',
    letterSpacing: 1,
  },
  title: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 33,
    lineHeight: 38,
    color: '#ffffff',
    letterSpacing: -0.6,
  },
  subtitle: {
    fontFamily: 'Manrope-Regular',
    fontSize: 15,
    lineHeight: 22,
    color: '#d8e7ff',
    maxWidth: 300,
  },
  statRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.14)',
    padding: 12,
    gap: 4,
  },
  statValue: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 22,
    color: '#ffffff',
  },
  statLabel: {
    fontFamily: 'Manrope-Medium',
    fontSize: 12,
    color: '#d8e7ff',
  },
  featuresWrap: {
    marginTop: 18,
    gap: 12,
  },
  featureCard: {
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dbe7ff',
    padding: 16,
    gap: 6,
  },
  featureTitle: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#0f1f36',
  },
  featureBody: {
    fontFamily: 'Manrope-Regular',
    fontSize: 13,
    lineHeight: 19,
    color: '#5f7087',
  },
  ctaBlock: {
    gap: 10,
  },
  primaryCta: {
    width: '100%',
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0051d5',
  },
  primaryCtaText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
    color: '#ffffff',
  },
  secondaryCta: {
    width: '100%',
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#b8cbef',
    backgroundColor: '#e9f1ff',
  },
  secondaryCtaText: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
    color: '#2f4d7b',
  },
});
