import { StyleSheet } from 'react-native';

export const newCategoryStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7F9FB',
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 140,
    gap: 24,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    gap: 12,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 2,
  },
  label: {
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#737784',
  },
  inputWrap: {
    height: 43,
    borderRadius: 12,
    backgroundColor: '#F2F4F6',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 12,
  },
  input: {
    flex: 1,
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#191C1E',
  },
  notesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  notesInput: {
    minHeight: 120,
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#6B7280',
    textAlignVertical: 'top',
  },
  amountCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    gap: 12,
    shadowColor: '#191C1E',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 40,
    elevation: 2,
  },
  amountTag: {
    marginLeft: 'auto',
    backgroundColor: '#00327D',
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  amountTagText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
    lineHeight: 16,
    color: '#FFFFFF',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  amountCurrency: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 36,
    color: '#C3C6D5',
    marginRight: 8,
  },
  amountValue: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 56,
    lineHeight: 66,
    color: '#00327D',
  },
  continueButton: {
    height: 68,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#D5E0F8',
  },
  continueText: {
    fontFamily: 'Manrope-ExtraBold',
    fontSize: 18,
    lineHeight: 28,
    color: '#0145A5',
  },
  actionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.85)',
  },
  primaryButton: {
    height: 62,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00327D',
  },
  primaryButtonText: {
    fontFamily: 'Manrope-Bold',
    fontSize: 18,
    color: '#FFFFFF',
  },
});
